name: Playwright Tests

on:
  push:
    branches:
      - nueva-rama
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd Test
          npm install

      - name: Install Playwright
        run: |
          npx playwright install chromium

      - name: Run Playwright tests
        run: |
          cd Test
          npx playwright test TestPrueba.spec.ts
